// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// GenCode is an autogenerated mock type for the GenCode type
type GenCode struct {
	mock.Mock
}

// Generate provides a mock function with given fields: codeLen
func (_m *GenCode) Generate(codeLen int) (string, error) {
	ret := _m.Called(codeLen)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (string, error)); ok {
		return rf(codeLen)
	}
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(codeLen)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(codeLen)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGenCode creates a new instance of GenCode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGenCode(t interface {
	mock.TestingT
	Cleanup(func())
}) *GenCode {
	mock := &GenCode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
