upstream bookmark_service {
    server bookmark_service:8080;
    server bookmark_service2:8080;
    server bookmark_service3:8080;
}

upstream portal {
    server portal:3000;
}

server {
    listen 80;
    server_name trikhai.codes www.trikhai.codes;

    location / {
        proxy_pass http://portal/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location /api/bookmark_service/ {
        proxy_pass http://bookmark_service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}