upstream bookmark_service {
    server bookmark_service:8080;
    server bookmark_service2:8080;
    server bookmark_service3:8080;
}

upstream portal {
    server portal:3000;
}

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://portal/;
    }

    
    location /api/bookmark_service/ {
        proxy_pass http://bookmark_service/;
        
    }
}