name: CD-Pipeline
on:
  push:
    branches:
      - main
jobs:
  cd_pipeline:
    runs-on: self-hosted
    steps:
      - name: Deploy application
        working-directory: /root/deploy/bookmark-service-deployment
        run: |
          echo "Deploying application..."

          git pull

          docker compose pull bookmark_service
          docker compose up -d --no-deps bookmark_service bookmark_service2 bookmark_service3
          docker system prune -f
